#!/root/kinetic_typo_vid/venv/bin/python3
"""
script_generator.py
Step 2-3 of the Shorts pipeline: the COMBINED script + headline + per-sentence
visual plan call.

Per pipeline_upgrade_spec.md, this is now ONE Groq call that produces, together:
  - the narration script (6-9 sentences, hook-first, concrete-grounded)
  - 5 headline options + a chosen headline
  - a Pexels search_term + asset_type (video|photo) for EACH sentence

Doing it in one call (instead of script-gen then per-sentence keyword-gen) means
the model sees the FULL script context when picking every keyword — which fixes
the generic/repetitive stock-footage problem the upgrade targets — and cuts a
Groq round-trip.

It is fed REAL article text + top community comments (fetched by
article_fetcher) instead of the old ≤400-char RSS blurb.

Uses Groq free API (fast, reliable, 30 req/min free). Sign up at console.groq.com.
Requires: environment variable GROQ_API_KEY
"""

import os
import re
import json
import time
import subprocess
from pathlib import Path

# Import the new provider-agnostic LLM client
import llm_client

# Auto-load .env for key
_env_path = Path(__file__).parent / ".env"
if _env_path.exists():
    for _line in _env_path.read_text().splitlines():
        _line = _line.strip()
        if _line and not _line.startswith("#") and "=" in _line:
            _k, _v = _line.split("=", 1)
            _k, _v = _k.strip(), _v.strip().strip('"').strip("'")
            if _k == "GROQ_API_KEY" and not os.environ.get(_k):
                os.environ[_k] = _v

GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"

# Word targets sized for ~33-45s Shorts at the +20% narration rate
# (~3.9 words/sec → 110-150 words ≈ 28-38s; we keep the +20% rate that's
# tuned for Shorts, accept landing around the lower end of the 30-60s goal).
MAX_WORDS = 150
MIN_WORDS = 110

# The combined call returns script + 5 headlines + beats for Remotion components.
# Reasoning models (GPT-OSS) draw their hidden reasoning from this SAME
# budget — 2048 truncated mid-JSON on real runs (finish_reason=length),
# so 4096 leaves room for reasoning + the full JSON payload.
COMBINED_MAX_TOKENS = 4096

# Banned filler loaded from config.py (allows env override)
from config import BANNED_FILLER

# Valid beat types matching src/ Remotion components
VALID_BEAT_TYPES = {
    "key_statement", "icon_text", "versus", "chart_counter",
    "chart_comparison", "chart_line", "quote_card", "map_location",
    "progress_meter", "before_after", "timeline", "process_flow"
}

# Required fields per beat type (validated post-LLM)
BEAT_REQUIRED_FIELDS = {
    "key_statement": ["emphasisWords"],
    "icon_text": ["icon"],
    "versus": ["left", "right"],
    "chart_counter": ["value", "label"],
    "chart_comparison": ["items"],
    "chart_line": ["points"],
    "quote_card": ["quote", "attribution"],
    "map_location": ["locationName", "latitude", "longitude"],
    "progress_meter": ["value", "maxValue", "label"],
    "before_after": ["beforeLabel", "afterLabel"],
    "timeline": ["events"],
    "process_flow": ["steps"],
}

ALLOWED_ICONS = {
    "warning", "money", "chip", "brain", "network", "shield",
    "chart", "robot", "globe", "lightning", "gear", "database",
    "cloud", "lock", "unlock", "user", "users", "target", "trend"
}


def _call_llm(messages: list[dict], temperature: float = 0.5,
              max_tokens: int = 1024,
              model_key: str = llm_client.DEFAULT_MODEL_KEY) -> str:
    """Wrapper over llm_client.call_llm for backward compatibility.

    Uses the specified model_key so the caller can choose the model.
    """
    return llm_client.call_llm(
        messages=messages,
        model_key=model_key,
        temperature=temperature,
        max_tokens=max_tokens,
    )


# ---------------------------------------------------------------------------
# Step 2-3 — Combined script + headline + per-sentence visual plan (ONE call)
# ---------------------------------------------------------------------------

COMBINED_SYSTEM_PROMPT = f"""You are writing a script for a short-form vertical
video (30-45 seconds) about a tech/AI news story, AND structuring it into BEATS
for Remotion motion-graphics components. Your only goal is to make someone stop
scrolling and watch to the end. The video has NO stock footage — visuals are
generated by code (Remotion components) driven by your beat data.

Audience: the GENERAL PUBLIC — people who do NOT work in tech, do not know what
an LLM/parameter/benchmark is. Plain words only.

SOURCE MATERIAL (fetched for you — use it; do NOT invent facts):
{{SOURCE}}

PART A — SCRIPT RULES:
1. HOOK (sentence 1, 0-3s): Open with a SPECIFIC, CONCRETE detail from the
   source — a real number, a named person/community/tool, or a surprising fact
   pulled from the article or the comments. Create a curiosity gap. NEVER open
   with "Imagine...", "What if...", "Have you ever...", "Picture this...". A
   vague generality ("a debate is brewing") is a failure.
2. SPECIFICITY: Use real names, real numbers, and quotes/paraphrased opinions
   from the article and comments. Vague paraphrase is a failure state.
3. EMOTIONAL ARC: Vary the tone sentence to sentence — curiosity/stakes,
   tension/conflict, relatable anxiety, then a turn or payoff. Do not stay flat
   and explanatory throughout.
4. HUMAN TOUCH: Write like telling a friend something wild you just read.
   Contractions fine. Mix short punchy sentences with longer ones. No corporate
   hedging, no press-release tone.
5. NO FILLER CLOSERS: NEVER end with "be a part of the conversation", "what do
   you think", or "let me know". End with a real payoff — an outcome, a striking
   implication, or a genuine open question tied to specific stakes.
6. LENGTH: 6-9 sentences total, {MIN_WORDS}-{MAX_WORDS} words. Each sentence is
   a distinct filmable beat. Aim for the middle of the word range.
7. PLAIN NARRATION: clean punctuation for text-to-speech, no jargon, no acronyms
   without explanation, no emojis/symbols/markdown, no brackets or directions.

PART B — HEADLINE + YOUTUBE METADATA RULES:
Generate 5 headline options (on-screen hook). Each must create a curiosity gap
using a CONCRETE noun from the story (a name, tool, number, or group) — not a
generic phrase. Under 8 words. The chosen_headline is the one you'd put on-screen
as the hook text.
Bad: "Coding Just Got Personal"
Good: "This Subreddit Banned ChatGPT Code"

ALSO generate:
- youtube_title: punchy, ≤60 chars, curiosity-gap, YouTube-SEO style (NOT the raw
  source title). Banned: "You won't believe", all-caps shouting, clickbait that
  doesn't match the content.
- youtube_description: 1-2 line short caption (≤200 chars) ending with relevant
  hashtags, suitable to paste into Shorts description box.

PART C — BEAT STRUCTURE RULES:
Convert the script into a sequence of BEATS. Each beat maps to ONE Remotion
component. Use these types (matching the component library):

- key_statement: {{text, emphasisWords: string[1-2], durationInFrames}}
- icon_text: {{text, icon: "warning"|"money"|"chip"|"brain"|"network"|"shield"|"chart"|"robot"|"globe"|"lightning"|"gear"|"database"|"cloud"|"lock"|"unlock"|"user"|"users"|"target"|"trend", durationInFrames}}
- versus: {{text, left: {{label, value?}}, right: {{label, value?}}, durationInFrames}}
- chart_counter: {{text, value: int, label: string, durationInFrames}}
- chart_comparison: {{text, items: [{{label, value}}], durationInFrames}}
- chart_line: {{text, points: [{{label, value}}], durationInFrames}}  (3-6 points showing a trend)
- quote_card: {{text, quote, attribution, durationInFrames}}
- map_location: {{text, locationName, latitude, longitude, durationInFrames}}
- progress_meter: {{text, value, maxValue, label, durationInFrames}}
- before_after: {{text, beforeLabel, afterLabel, durationInFrames}}
- timeline: {{text, events: [{{marker, label}}], durationInFrames}}  (2-5 events)
- process_flow: {{text, steps: string[2-4], durationInFrames}}

Rules:
- Every beat MUST have `text` (narration for this beat) and `durationInFrames`
  (estimated from word count @ ~2.5 words/sec → frames = words/2.5*30).
- Use ONLY data from source (anti-fabrication). If no real data for a specific
  type → use key_statement.
- Vary types. Prefer specific types when source supports them:
  numbers → chart_counter, comparisons → versus/chart_comparison,
  quotes → quote_card, places → map_location, percentages → progress_meter,
  clear before/after → before_after, sequences → timeline/process_flow.
- Beat count: 6-12 (more granular than sentences).
- Output JSON key: "beats" (not "shots").

OUTPUT FORMAT (strict JSON, no markdown fences, no preamble):
{{
  "headline_options": ["...", "...", "...", "...", "..."],
  "chosen_headline": "...",
  "youtube_title": "...",
  "youtube_description": "...",
  "beats": [
    {{
      "type": "versus",
      "text": "US pushes allies to pick a side, China pushes back.",
      "left": {{"label": "US", "value": "American ecosystem"}},
      "right": {{"label": "China", "value": "Chinese ecosystem"}},
      "durationInFrames": 90
    }},
    {{
      "type": "chart_counter",
      "text": "EU has 6% of world population but 15% of researchers.",
      "value": 6,
      "label": "percent of world population",
      "durationInFrames": 75
    }},
    {{
      "type": "key_statement",
      "text": "The AI race is now geopolitical.",
      "emphasisWords": ["geopolitical"],
      "durationInFrames": 60
    }}
  ]
}}
The "beats" array length MUST be 6-12.
Each beat MUST have "type", "text", "durationInFrames", and the required fields for its type.
"""


def _source_block(story: dict, content: dict) -> str:
    """Build the SOURCE MATERIAL block from fetched content (hfed into the prompt)."""
    parts = [
        f"Title: {story.get('title','')}",
        f"Source: {story.get('source','')}",
    ]
    body = (content.get("article_text") or "").strip()
    parts.append(f"Article body: {body if body else '(no article text — rely on the title and your judgement)'}")
    comments = content.get("comments") or []
    if comments:
        cblock = "\n".join(f"- {c}" for c in comments)
        parts.append(f"Community discussion (comments):\n{cblock}")
    return "\n".join(parts)


def generate_combined(story: dict, content: dict,
                     retry_feedback: str = "",
                     model_key: str = llm_client.DEFAULT_MODEL_KEY) -> dict:
    """One LLM call → script + headlines + per-sentence plan. Validates + retries once.

    Returns a dict: {script, headline_options, chosen_headline, youtube_title,
    youtube_description, shots, word_count}.
    `shots` is the per-sentence list with sentence/search_term/asset_type, in
    order. `script` is reconstructed by joining shot sentences (so the script
    and the plan are guaranteed to have the same sentence count — this kills a
    whole class of drift between script, captions, and assembly).
    """
    source = _source_block(story, content)
    system = COMBINED_SYSTEM_PROMPT.replace("{SOURCE}", source)
    user_prompt = "Write the script + 5 headlines + per-sentence shots now."
    messages = [
        {"role": "system", "content": system},
        {"role": "user", "content": user_prompt},
    ]
    if retry_feedback:
        messages.append({"role": "assistant", "content": "(previous output rejected)"})
        messages.append({"role": "user", "content": retry_feedback})

    raw = _call_llm(messages, temperature=0.7, max_tokens=COMBINED_MAX_TOKENS, model_key=model_key)
    if not raw or not raw.strip():
        raise RuntimeError(f"LLM returned empty response for model '{model_key}'")
    parsed = _parse_combined(raw)
    if not parsed:
        raise RuntimeError(f"LLM combined output was not valid JSON: {raw[:200]}")

    # Validate — one retry if banned filler or near-duplicate search terms slip in.
    problems = _validate(parsed, story)
    if problems and not retry_feedback:   # retry exactly once
        fb = "Your previous output had these problems; fix them and return the full JSON again:\n- " + "\n- ".join(problems)
        print(f"  [validator] retrying: {len(problems)} issue(s): {problems[0]}")
        return generate_combined(story, content, retry_feedback=fb)

    # Normalize beats
    beats = []
    for b in parsed.get("beats", []):
        beat_type = b.get("type")
        if beat_type not in VALID_BEAT_TYPES:
            continue
        # Ensure required fields exist (validator already checked, but guard anyway)
        normalized = {"type": beat_type}
        for key, val in b.items():
            if key == "type":
                continue
            normalized[key] = val
        # Ensure durationInFrames is int
        if "durationInFrames" in normalized:
            try:
                normalized["durationInFrames"] = int(normalized["durationInFrames"])
            except (ValueError, TypeError):
                normalized["durationInFrames"] = 60
        beats.append(normalized)
    
    script = " ".join(b["text"] for b in beats if b.get("text")).strip()
    word_count = len(script.split())

    # Calculate script quality metrics
    beat_texts = [b["text"] for b in beats if b.get("text")]
    all_words = " ".join(beat_texts).lower().split()
    unique_words = set(all_words)
    lexical_diversity = len(unique_words) / len(all_words) if all_words else 0
    
    beat_lengths = [len(t.split()) for t in beat_texts]
    avg_beat_len = sum(beat_lengths) / len(beat_lengths) if beat_lengths else 0
    beat_len_variance = sum((l - avg_beat_len) ** 2 for l in beat_lengths) / len(beat_lengths) if beat_lengths else 0
    
    quality_metrics = {
        "word_count": word_count,
        "beat_count": len(beats),
        "lexical_diversity": round(lexical_diversity, 3),
        "avg_beat_length": round(avg_beat_len, 1),
        "beat_length_variance": round(beat_len_variance, 1),
        "unique_words": len(unique_words),
    }

    return {
        "script": script,
        "headline_options": parsed.get("headline_options", []),
        "headline": (parsed.get("chosen_headline") or "").strip(),
        "youtube_title": (parsed.get("youtube_title") or "").strip(),
        "youtube_description": (parsed.get("youtube_description") or "").strip(),
        "beats": beats,
        "word_count": word_count,
        "quality_metrics": quality_metrics,
    }


def _parse_combined(raw: str) -> dict | None:
    """Parse the combined JSON, tolerating markdown fences / extra prose."""
    if not raw:
        return None
    txt = raw.strip()
    # strip ```json fences if present
    txt = re.sub(r"^```(?:json)?|```$", "", txt, flags=re.MULTILINE).strip()
    # if there's stray prose around the JSON, grab the first {...} block
    if not txt.startswith("{"):
        m = re.search(r"\{.*\}", txt, flags=re.DOTALL)
        if m:
            txt = m.group(0)
    try:
        obj = json.loads(txt)
    except json.JSONDecodeError:
        return None
    if not isinstance(obj, dict):
        return None
    if "beats" not in obj or not isinstance(obj["beats"], list):
        return None
    return obj


def _normalize_term(t: str) -> str:
    """Normalize a search term for near-duplicate comparison."""
    return re.sub(r"[^a-z0-9]+", " ", (t or "").lower()).strip()


def _validate(parsed: dict, story: dict = None) -> list[str]:
    """Return a list of problems that warrant a single rewrite (empty = OK).

    - any beat text contains a banned filler phrase
    - beat type not in VALID_BEAT_TYPES
    - missing required fields for beat type
    - beat count outside 6-12
    - youtube_title missing, empty, or >60 chars
    - youtube_description missing, empty, or >200 chars
    - headline relevance to source (if story provided)
    """
    problems = []
    beats = parsed.get("beats", [])
    if not (6 <= len(beats) <= 12):
        problems.append(f"beat count {len(beats)} is outside the 6-12 target")
    
    for i, beat in enumerate(beats):
        beat_type = beat.get("type")
        text = (beat.get("text") or "").strip()
        low = text.lower()
        
        # Banned filler
        for b in BANNED_FILLER:
            if low.startswith(b) or (" " + b) in low or low == b:
                problems.append(f'beat {i} text contains banned filler "{b}": "{text[:50]}"')
                break
        
        # Valid type
        if beat_type not in VALID_BEAT_TYPES:
            problems.append(f'beat {i} has invalid type "{beat_type}"')
            continue
        
        # Required fields per type
        required = BEAT_REQUIRED_FIELDS.get(beat_type, [])
        for field in required:
            if field not in beat or beat[field] in (None, "", [], {}):
                problems.append(f'beat {i} ({beat_type}) missing required field: {field}')
        
        # durationInFrames required for all
        if "durationInFrames" not in beat or not isinstance(beat["durationInFrames"], int) or beat["durationInFrames"] <= 0:
            problems.append(f'beat {i} ({beat_type}) missing or invalid durationInFrames')
        
        # icon_text: icon must be in ALLOWED_ICONS
        if beat_type == "icon_text":
            icon = beat.get("icon")
            if icon not in ALLOWED_ICONS:
                problems.append(f'beat {i} icon_text has invalid icon "{icon}" (allowed: {sorted(ALLOWED_ICONS)})')
        
        # chart_line: points must be 3-6
        if beat_type == "chart_line":
            points = beat.get("points", [])
            if not (3 <= len(points) <= 6):
                problems.append(f'beat {i} chart_line needs 3-6 points, got {len(points)}')
        
        # timeline: events must be 2-5
        if beat_type == "timeline":
            events = beat.get("events", [])
            if not (2 <= len(events) <= 5):
                problems.append(f'beat {i} timeline needs 2-5 events, got {len(events)}')
        
        # process_flow: steps must be 2-4
        if beat_type == "process_flow":
            steps = beat.get("steps", [])
            if not (2 <= len(steps) <= 4):
                problems.append(f'beat {i} process_flow needs 2-4 steps, got {len(steps)}')
    
    # headline sanity
    if not parsed.get("chosen_headline"):
        problems.append("missing chosen_headline")
    elif story:
        headline = parsed.get("chosen_headline", "").lower()
        source_text = (story.get("title", "") + " " + story.get("summary", "")).lower()
        headline_words = set(re.findall(r'\b\w{4,}\b', headline))
        source_words = set(re.findall(r'\b\w{4,}\b', source_text))
        if headline_words and source_words:
            overlap = headline_words & source_words
            if not overlap:
                problems.append(f'headline "{parsed.get("chosen_headline")}" shares no meaningful words with source title/summary')
        
        has_number = bool(re.search(r'\b\d+[kKmMbB%]?\b', parsed.get("chosen_headline", "")))
        has_proper_noun = bool(re.search(r'\b[A-Z][a-z]+\b', parsed.get("chosen_headline", "")))
        if not (has_number or has_proper_noun):
            problems.append(f'headline "{parsed.get("chosen_headline")}" lacks specific entity (number, name, or proper noun) — make it concrete')
    
    # Validate headline options
    for opt in parsed.get("headline_options", []):
        opt_lower = opt.lower()
        opt_words = set(re.findall(r'\b\w{4,}\b', opt_lower))
        if opt_words and story and source_words:
            overlap = opt_words & source_words
            if not overlap:
                problems.append(f'headline option "{opt}" shares no meaningful words with source')
                break
    
    # youtube metadata sanity
    yt_title = (parsed.get("youtube_title") or "").strip()
    if not yt_title:
        problems.append("missing youtube_title")
    elif len(yt_title) > 60:
        problems.append(f"youtube_title exceeds 60 chars ({len(yt_title)})")
    yt_desc = (parsed.get("youtube_description") or "").strip()
    if not yt_desc:
        problems.append("missing youtube_description")
    elif len(yt_desc) > 200:
        problems.append(f"youtube_description exceeds 200 chars ({len(yt_desc)})")
    return problems


def process_story(story: dict, content: dict | None = None,
                  model_key: str = llm_client.DEFAULT_MODEL_KEY) -> dict:
    """End-to-end Step 2-3 for one story: ONE combined LLM call.

    Now fetches real article text + comments (via article_fetcher) and produces
    a script + 5 headline options + chosen headline + BEATS for Remotion components
    in a single LLM round-trip, then validates (banned filler, beat structure)
    with one retry pass.

    `content` is the dict from article_fetcher.fetch_article_content(). When
    None, it is fetched here (so standalone `python script_generator.py` works).
    """
    # --- Step 1.5: fetch real content (unless the caller already did) ---
    if content is None:
        from article_fetcher import fetch_article_content
        content = fetch_article_content(story)

    print(f"Writing script + headlines + visual plan: {story['title'][:60]}...")
    result = generate_combined(story, content, model_key=model_key)
    script = result["script"]
    print(f"  ✓ script ({result['word_count']} words, "
          f"{len(result['shots'])} shots, headline: \"{result['headline']}\")")

    # Lightweight research_notes.json (kept for downstream / metadata parity).
    # The combined call supersedes the old separate research step — the raw
    # article IS the research now, so we keep a small summary for the artifact.
    research = {
        "source_kind": content.get("source_kind", "rss"),
        "used_fallback": content.get("used_fallback", False),
        "fallback_reason": content.get("fallback_reason", ""),
        "article_chars": content.get("article_chars", 0),
        "comment_count": content.get("comment_count", 0),
        "headline_options": result.get("headline_options", []),
        "fetched_at": content.get("fetched_at", ""),
    }
    result["research"] = research
    result["story"] = story
    return result


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1].startswith("http"):
        # live-fetch a real article and process it
        from article_fetcher import fetch_article_content
        story = {"title": "(from URL)", "source": "cli", "link": sys.argv[1], "summary": ""}
        res = process_story(story)
        print(json.dumps({k: v for k, v in res.items() if k != "story"},
                         indent=2)[:4000])
    else:
        test_story = {
            "title": "Google DeepMind reshuffle — Demis Hassabis moves from CEO to chair",
            "source": "TLDR AI",
            "link": "https://example.com",
            "summary": "Hassabis moves to chair; a new head of Gemini takes the CEO role.",
        }
        result = process_story(test_story)
        out = {k: v for k, v in result.items() if k != "story"}
        # Pretty print beats
        if "beats" in out:
            print(f"Script: {out['script']}")
            print(f"Word count: {out['word_count']}")
            print(f"Beats ({len(out['beats'])}):")
            for i, b in enumerate(out['beats']):
                print(f"  {i+1}. [{b['type']}] {b['text'][:60]}... ({b.get('durationInFrames', '?')} frames)")
        print(json.dumps(out, indent=2)[:4000])
