import { registerRoot } from "remotion";
import {
  BackgroundTest,
  KineticCaptionsComposition,
  KineticCaptionsTest1,
  KineticCaptionsTest2,
  ChartCounterTest,
  ChartComparisonTest,
  IconTextTest,
  KeyStatementTest,
  TimelineTest,
  ProcessFlowTest,
  VersusCardTest,
  ChartLineTest,
  MapLocationTest,
  QuoteCardTest,
  ProgressMeterTest,
  BeforeAfterTest,
  MotionGraphicsVideoComposition,
  KeyStatementLongTest,
  KeyStatementShortTest,
} from "./index";

registerRoot({
  BackgroundTest,
  KineticCaptionsComposition,
  KineticCaptionsTest1,
  KineticCaptionsTest2,
  ChartCounterTest,
  ChartComparisonTest,
  IconTextTest,
  KeyStatementTest,
  KeyStatementLongTest,
  KeyStatementShortTest,
  TimelineTest,
  ProcessFlowTest,
  VersusCardTest,
  ChartLineTest,
  MapLocationTest,
  QuoteCardTest,
  ProgressMeterTest,
  BeforeAfterTest,
  MotionGraphicsVideoComposition,
});
